---
- name: Simulate network zone setup
  hosts: all
  gather_facts: false

  tasks:
    - name: Display defined VLANs
      debug:
        var: vlans

    - name: Display defined firewall rules
      debug:
        var: firewall_rules
