---
# Global variables
ansible_python_interpreter: /usr/bin/python3

vlans:
  - { id: 20, name: "MGMT", subnet: "172.20.0.0/24" }
  - { id: 21, name: "DMZ", subnet: "172.21.0.0/24" }
  - { id: 22, name: "INTERNAL", subnet: "172.22.0.0/24" }
  - { id: 23, name: "SECURE", subnet: "172.23.0.0/24" }

firewall_rules:
  - { zone: "dmz", allow: ["80/tcp", "443/tcp"] }
  - { zone: "internal", allow: ["8080/tcp"] }
  - { zone: "secure", allow: ["3306/tcp"] }
  - { zone: "mgmt", allow: ["22/tcp"] }
