---
# Virtual network zones definition
vlans:
  - id: 10
    name: dmz
    subnet: 192.168.10.0/24
  - id: 20
    name: internal
    subnet: 192.168.20.0/24
  - id: 30
    name: secure
    subnet: 192.168.30.0/24

# Example firewall rules (logical only for now)
firewall_rules:
  - name: allow_http_dmz
    src: any
    dst: 192.168.10.0/24
    port: 80
    action: allow
  - name: allow_app_to_db
    src: 192.168.20.0/24
    dst: 192.168.30.0/24
    port: 3306
    action: allow
  - name: deny_all
    src: any
    dst: any
    port: any
    action: deny
